# 180621 Reza Farrahi (imriss@yahoo.com)
version: "3.3"
services:
  # agent section
  datadog:
    build: datadog
    environment:
      - API_KEY=<<API_KEY>>
      - TAGS="<<tag 1>>, <<tag 2>>"
      - CHECKSD_OVERRIDE=/opt/datadog-agent/agent/checks.d/
    volumes:
      - /shared-mount-point/:/shared-mount-point:ro
    networks:
      - datadog

networks:
  datadog:
    driver: bridge
